version: '2'
services:
  mysql_manager:
    image: mysql
    container_name: eosai_manager_mysql
    ports:
      - 3306:3306
    environment:
      - MYSQL_DATABASE=cmems_manager
      - MYSQL_USER=cmems
      - MYSQL_PASSWORD=cmems
      - MYSQL_ROOT_PASSWORD=cmems
  processors:
    image: planetek/eosai_processors:develop
    container_name: eosai_processors
    volumes:
      - /home/francesco/cmems/pkz029_UU_CMEMS_dockerized/shared_data/C5_OutputDir:/src/Processors/server/processors/C5_OutputDir
      - /home/francesco/cmems/pkz029_UU_CMEMS_dockerized/shared_data/C3_Input:/src/Processors/server/processors/C3_Input
    ports:
      - 9091:9091
